# Generated by Django 4.2.5 on 2024-07-11 15:03

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.product_image_path)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('num_bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('num_floors', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
